TARGET = arch
SOURCES = arch.cpp
mac:CONFIG -= app_bundle

!isEmpty(QMAKE_CFLAGS_AVX2):QMAKE_CXXFLAGS += $$QMAKE_CFLAGS_AVX2
else:!isEmpty(QMAKE_CFLAGS_AVX):QMAKE_CXXFLAGS += $$QMAKE_CFLAGS_AVX
else:!isEmpty(QMAKE_CFLAGS_SSE4_2):QMAKE_CXXFLAGS += $$QMAKE_CFLAGS_SSE4_2
else:!isEmpty(QMAKE_CFLAGS_SSE4_1):QMAKE_CXXFLAGS += $$QMAKE_CFLAGS_SSE4_1
else:!isEmpty(QMAKE_CFLAGS_SSSE3):QMAKE_CXXFLAGS += $$QMAKE_CFLAGS_SSSE3
else:!isEmpty(QMAKE_CFLAGS_SSE3):QMAKE_CXXFLAGS += $$QMAKE_CFLAGS_SSE3
else:!isEmpty(QMAKE_CFLAGS_SSE2):QMAKE_CXXFLAGS += $$QMAKE_CFLAGS_SSE2
else:!isEmpty(QMAKE_CFLAGS_NEON):QMAKE_CXXFLAGS += $$QMAKE_CFLAGS_NEON